# Introduction
<hr style="border:2px solid black"> </hr>


**What?** Tensor manipulation in PyTorch



# Import python modules

In [1]:
import torch
import numpy as np

# Tensor Initialization from data

In [4]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(type(x_data))
x_data

<class 'torch.Tensor'>


tensor([[1, 2],
        [3, 4]])

# Tensor initialisation from numpy array

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(type(x_np))
x_np

<class 'torch.Tensor'>


tensor([[1, 2],
        [3, 4]])

# Tensor initialisation from another tensor

In [ ]:
"""
The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
"""

In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

# Curly brackets avoid you to use the comma!
print(f"Ones Tensor: \n", x_ones, "\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5935, 0.0447],
        [0.4546, 0.5183]]) 



# Tensor initialisation with random or constant values

In [ ]:
"""
shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the 
output tensor.
"""

In [19]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7504, 0.6583, 0.7440],
        [0.4824, 0.3476, 0.8327]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [16]:
"""
What happens if I use (2,3) instead? Nothing the output is the same
"""

'\nWhat happens if I use (2,3) instead?\n'

In [21]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3386, 0.5160, 0.6497],
        [0.0307, 0.9436, 0.4188]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Tensor attributes

In [ ]:
"""
Tensor attributes describe their shape, datatype, and the device on which they are stored.
"""

In [23]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print("Shape of tensor:", tensor.shape)
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Tensor operations

In [ ]:
"""
Over 100 tensor operations are described here:
https://pytorch.org/docs/stable/torch.html
"""

In [26]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    print("GPUs available")
    tensor = tensor.to('cuda')
else:
    print("GPUs not available!")

GPUs not available!


In [30]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)
print("Device tensor is stored on: ", tensor.device)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
Device tensor is stored on:  cpu


# References
<hr style="border:2px solid black"> </hr>


- https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

