# Introduction to this python notebook

In [ ]:
"""
What? Working with tensors in pytorch

Reference: Jibin Mathew. “PyTorch Artificial Intelligence Fundamentals
"""

# Import python modules

In [38]:
import torch
import numpy as np

# Tensor in pytorch

In [3]:
torch.ones((2,), dtype=torch.int8)

tensor([1, 1], dtype=torch.int8)

In [4]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.ones((2,3),dtype=torch.int8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)

In [6]:
torch.zeros((2,3), dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [12]:
torch.zeros((2,3)).dtype

torch.float32

In [13]:
torch.empty((2,3))

tensor([[0.0000e+00, 1.0842e-19, 0.0000e+00],
        [1.0842e-19, 9.8091e-45, 0.0000e+00]])

In [14]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [15]:
torch.full((2, 3), 3)

tensor([[3, 3, 3],
        [3, 3, 3]])

In [16]:
torch.rand((2,3))

tensor([[0.1529, 0.2280, 0.1626],
        [0.4177, 0.6197, 0.1110]])

In [20]:
# with lower and upper limit of a random tensor
torch.randint(10, 100, (2,3))

tensor([[32, 87, 88],
        [31, 67, 96]])

In [21]:
torch.randn((2,3))

tensor([[ 1.2159,  1.8919,  0.2621],
        [-0.2897, -0.4806, -0.4720]])

In [22]:
torch.tensor([[1, 2 ,3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
torch.as_tensor([[1., 2 ,3], [4, 5, 6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [25]:
a = torch.tensor([[1, 2 ,3], [4, 5, 6]])

In [26]:
a.dtype

torch.int64

In [27]:
a.shape

torch.Size([2, 3])

In [28]:
b = torch.ones_like(a)

In [29]:
b

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
a.new_tensor([[0., 1.]])

<ipython-input-37-deef8729db88>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  a.new_tensor([[0., 1.]])


tensor([[0, 1]])

In [31]:
# We can use the torch.new_* format to create a tensor with a similar TYPE
# to another tensor, but a different size.
a.new_full((2,2), 3.)

tensor([[3, 3],
        [3, 3]])

In [32]:
a.size()

torch.Size([2, 3])

In [33]:
a.dtype

torch.int64

In [35]:
b

tensor([[1, 1, 1],
        [1, 1, 1]])

In [36]:
b.numel()

6

# The bridge with numpy

In [ ]:
"""
NumPy is the standard Python library and is used to deal with numerical data. Many well-known ML/DS libraries 
in Python, such as pandas (a library that is used to read data from many sources) and scikit-learn (one of the
most important ML libraries, used to read and write images) use NumPy under the hood. You will deal with numpy a
lot, for example, while dealing with tabular data, loading it using the pandas library and getting numpy arrays 
out of the dataframe; reading images, where many existing libraries have in-built APIs for reading them as numpy 
arrays; and also converting numpy arrays into images, as well as text and other forms of data. Also, these all 
support numpy arrays using scikit-learn, which is a machine learning library. As you can see, it is important to
have a bridge between numpy arrays and PyTorch tensors.
"""

In [39]:
a = np.random.rand(2,3)
a

array([[0.31250357, 0.30933192, 0.78090067],
       [0.9765697 , 0.39101414, 0.29708657]])

In [40]:
a = np.ones((2, 3))

In [41]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
b = torch.from_numpy(a)

In [43]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [44]:
# Retunr to the numpy version of the data
b.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
a *= 2

In [46]:
a

array([[2., 2., 2.],
       [2., 2., 2.]])

In [47]:
# We can see that the changes from the numpy are reflected in the tensor as well.
b

tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

# Exploring gradietns

In [ ]:
"""
The Autograd module in PyTorch performs all gradient calculations in PyTorch. It is the core Torch package for
automatic differentiation. It uses a tape-based system for automatic differentiation. In the forward phase, the
Autograd tape will remember all the operations it executed, and in the backward phase it will replay them.
"""

In [48]:
b = torch.ones((2,3))

In [49]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [50]:
b.requires_grad

False

In [51]:
a = torch.ones((2,3),requires_grad=True)

In [52]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [56]:
a.requires_grad

True

In [58]:
# Note that is important you use the dot after 4., because a gradient will not be computed if you use integer
a = torch.full((2,3), 4., requires_grad=True)

In [67]:
a

tensor([[4., 4., 4.],
        [4., 4., 4.]], requires_grad=True)

In [74]:
a**2+3

tensor([[19., 19., 19.],
        [19., 19., 19.]], grad_fn=<AddBackward0>)

In [83]:
b = (a**2+3).sum()

In [84]:
b

tensor(114., grad_fn=<SumBackward0>)

In [85]:
b.grad_fn

In [86]:
b.requires_grad

True

In [87]:
b.backward()

In [88]:
a.grad

tensor([[24., 24., 24.],
        [24., 24., 24.]])

In [90]:
x = torch.full((2,3), 4.,requires_grad=True)

In [91]:
x

tensor([[4., 4., 4.],
        [4., 4., 4.]], requires_grad=True)

In [92]:
y = 2*x+3

In [93]:
y

tensor([[11., 11., 11.],
        [11., 11., 11.]], grad_fn=<AddBackward0>)

In [94]:
x

tensor([[4., 4., 4.],
        [4., 4., 4.]], requires_grad=True)

In [95]:
y = (2*x**2+3)

In [96]:
y

tensor([[35., 35., 35.],
        [35., 35., 35.]], grad_fn=<AddBackward0>)

In [97]:
y.backward(torch.ones_like(x))

In [127]:
x.grad

tensor([[16., 16., 16.],
        [16., 16., 16.]])

In [128]:
y.grad

In [129]:
x.requires_grad

True

In [130]:
x.requires_grad_(False)

tensor([[4., 4., 4.],
        [4., 4., 4.]])

In [131]:
x.requires_grad

False

In [139]:
x.requires_grad

True

In [98]:
with torch.no_grad():
    print(x.requires_grad)

True


In [99]:
y.requires_grad

True

In [ ]:
"""
PyTorch has a package called autograd that performs all the tracking and automatic differentiation for all 
operations on tensors. It is a define-by-run framework, which means that your backpropagation is defined by
how your code is run and that every single iteration can be different. 
"""

In [102]:
x = torch.randn(3, requires_grad=True)
print(x.requires_grad)
print((x ** 2).requires_grad)
y = x**2
print(y.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)
    print(y.requires_grad)

True
True
True
False
True


# Viewing tensors in PyTorch

In [103]:
a = torch.Tensor([1, 2, 3, 4])
a

tensor([1., 2., 3., 4.])

In [104]:
torch.reshape(a, (2, 2))

tensor([[1., 2.],
        [3., 4.]])

In [105]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.resize_((2, 2))

tensor([[1., 2.],
        [3., 4.]])

In [161]:
torch.arange(1.,7.).resize_(2,3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [163]:
torch.arange(1.,7.)

tensor([1., 2., 3., 4., 5., 6.])

In [172]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.view((2, -1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [173]:
a = torch.Tensor([1, 2, 3, 4, 5, 6])
a.view((2, 3))

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [179]:
a = torch.Tensor([[1, 2, 3], 
                 [4, 5, 6]])
b = torch.Tensor([4,5,6,7,8,9])

In [180]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [181]:
b

tensor([4., 5., 6., 7., 8., 9.])

In [182]:
b.view_as(a)

tensor([[4., 5., 6.],
        [7., 8., 9.]])

In [183]:
b

tensor([4., 5., 6., 7., 8., 9.])